require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/omniauth-sageone.rb'

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/FilePath:
  Exclude:
    - 'spec/omniauth/strategies/sage_one_spec.rb'
