AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/omniauth-sageone.rb'

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'
